use_default_settings: true

general:
  instance_name: "Seek"

search:
  formats:
    - html
    - json

server:
  secret_key: "seekmcpsecretchangeme"
  limiter: false
  public_instance: false

ui:
  cache_url: ""
